### ISSUE TITLE
All displays are blank

### ISSUE THREAD

**Issue by ChefKissInc** [NootInc/WhateverRed#10]
All displays are blank. Investigation is in progress. This is for progress tracking

**Comment by someusern** [comment]
look whatever green black display fix (maybe this is the only solution?)

**Comment by SsNiPeR1** [comment]
@someusern this kext does not work without whatevergreen at all bro

**Comment by ChefKissInc** [comment]
@SsNiPeR1 Please do not respond on our behalf! And this seems to be incorrect information

**Comment by ChefKissInc** [comment]
@someusern The display is not being programmed correctly as it is newer technology than the GCN 5 (AMDRadeonX5000) kexts expect. This is not a simple “duct tape”-able issue. 
Also, we’re already using WhateverGreen, but we aren’t sure how much patching it’s doing as there is a Lilu bug that prevents multiply-nested devices from being detected (such us AMD iGPUs, path for 99% of dGPUs is something like PCI0.GPP8.blah, while for AMD iGPUs it is PCI0.GPP8.IOPP.blah)
We wish it was as simple as just some random black screen fix. Haha

**Comment by someusern** [comment]
I understand

**Comment by ChefKissInc** [comment]
Resolved in latest commits!
