### ISSUE TITLE
Handle VBIOS extraction when the iGPU one is put in the VRAM

### ISSUE THREAD

**Issue by NyanCatTW1** [NootInc/WhateverRed#15]
Quoting from README.md:
> Can I have an AMD dGPU installed on the system?
> 
> We are mixing AMDRadeonX5000 for GCN 5, AMDRadeonX6000 for VCN, and AMDRadeonX6000Framebuffer for DCN, so your system must not have a GCN 5 or RDNA AMD dGPU, as this kext will conflict with them.
> 
> Also, if you have any AMD dGPU installed, it is likely that the VBIOS in the VFCT ACPI table will be overriden with the one from the dGPU, and the one from the iGPU will be put in its VRAM, which we do not currently handle.

**Comment by ChefKissInc** [comment]
NC, this is not planned.

**Comment by ChefKissInc** [comment]
Whoops, this might be needed on some systems

**Comment by ChefKissInc** [comment]
Implemented
