### ISSUE TITLE
Big Sur is losing support this year

### ISSUE THREAD

**Issue by Im-Mefju** [NootInc/WhateverRed#16]
So im wondering if we are stuck on Big Sur forever or there will be some way later to update? Even at the cost of losing sip

**Comment by ChefKissInc** [comment]
Have you tried *reading the README*

**Comment by ChefKissInc** [comment]
Clarification: We do not implement solutions that aren't clean. You might have to rely on external support for this. If we find a way to inject to the auxiliary cache without breaking the seal, we'll probably implement it.
